= Site
Malcolm Sparks <mal@juxt.pro>
v1.0, 2022-06-21
:doctype: book
:toc: left
:toclevels: 2
:sectnums:
:sectnumlevels: 4
:xrefstyle: short
:stem:

[colophon]
--
First Edition.

Copyright © 2023, JUXT LTD. All Rights Reserved.

Published by JUXT Text.

This book is written with Asciidoctor.

Available in PDF, ebook and HTML editions.

HTML edition available at https://text.juxt.site/site-book.html

--

toc::[]

include::Introduction.adoc[leveloffset=+1]

=== Values & Principles

include::Values.adoc[leveloffset=+3]

include::Principles.adoc[leveloffset=+3]

= Getting Started

Follow this guide to get up-and-running with your very own Site instance, running locally on your machine.
If you wish to install Site in production, refer to <<pt-deployment>>.

[NOTE]
--
All these instructions are for Arch Linux, please amend accordingly for your own platform, if different.
Run each command under your user account (i.e. not as root).
--

include::GettingStarted/Preparation.adoc[leveloffset=+1]

include::GettingStarted/Startup.adoc[leveloffset=+1]

include::GettingStarted/Bootstrapping.adoc[leveloffset=+1]

include::GettingStarted/Client.adoc[leveloffset=+1]

include::GettingStarted/Users.adoc[leveloffset=+1]

include::GettingStarted/Conclusion.adoc[leveloffset=+1]

= Foundations

In keeping with our value of <<understanding,Understanding>>, we recommended that you invest time in building up both your working and conceptual knowledge of Site.

The chapters in this part of the book will help to build up your knowledge of Site 'from scratch'.

include::Concepts.adoc[leveloffset=+1]

include::BootstrappingSite.adoc[leveloffset=+1]

include::CreatingActions.adoc[leveloffset=+2]

// TODO: Gently move sections from Operations.adoc and Permissions.adoc into chapters here

// TODO: Include a chapter on SCI

[[ch-operations]]
include::Operations.adoc[leveloffset=+1]

////
include::Permissions.adoc[leveloffset=+0]
[[ch-subjects]]
include::Subjects.adoc[leveloffset=+1]
[[ch-creating-users]]
include::UsersRevisited.adoc[leveloffset=+2]
////

[[ch-resources]]
include::Resources.adoc[leveloffset=+1]

include::Representations.adoc[leveloffset=+1]

= Authentication

(((authentication, definition)))
Authentication is the process by which a user is identified.

(((access control)))
In Site, Operations are integrated with authorization rules, providing a rich access control
layer between users and data.

(((Subject)))
Most authorization rules refer to the Subject of the request. To identify the
Subject, we need to authenticate each request.

Site supports two types of user authentication:

(((authentication,HTTP))) *HTTP Authentication*, which introduces the concept of _protection spaces_, specified in cite:[rfc7235], is described in <<ch-http-authentication>>.
An example of HTTP Authentication is the 'Basic' authentication scheme, which is covered in <<ch-basic-authentication>>.

(((authentication,session-based))) *Session-based Authentication*, which we describe in <<ch-session-authentication>>, opens up numerous additional options for authentication.
One such option is authenticating via an HTML form, which is covered in <<ch-form-based-authentication>>.
Another is with the OpenID Connect protocol, which is covered in <<ch-openid>> with a worked example.

include::ProtectingResources.adoc[leveloffset=+1]

[[ch-http-authentication]]
include::HttpAuthentication.adoc[leveloffset=+1]

[[ch-basic-authentication]]
include::BasicAuthentication.adoc[leveloffset=+1]

[[ch-sessions]]
include::Sessions.adoc[leveloffset=+1]

[[ch-form-based-authentication]]
include::FormBasedAuthentication.adoc[leveloffset=+1]

[[ch-openid]]
include::OpenIdAuthentication.adoc[leveloffset=+1]

= Applications and APIs

First, in <<ch-applications>>, we introduce applications and create the required actions.

We start by configuring our authorization server in <<ch-authorization-server>>.

Then, in <<ch-first-application>>, we create an example application.

[[ch-applications]]
include::Applications.adoc[leveloffset=+1]

[[ch-authorization-server]]
include::AuthorizationServer.adoc[leveloffset=+1]

[[ch-first-application]]
include::FirstApplication.adoc[leveloffset=+1]

[[ch-openapi]]
include::OpenAPI.adoc[leveloffset=+1]

[[ch-graphql]]
include::GraphQL.adoc[leveloffset=+1]

[[pt-deployment]]
= Deployment

This is the forthcoming part on Site deployment.

= Going Further

[[ch-token-introspection]]
include::GSTokenIntrospection.adoc[leveloffset=+1]

[[ch-openapi]]
include::GSOpenAPI.adoc[leveloffset=+1]

include::ErrorResources.adoc[leveloffset=+1]

// Create an operation to list-identities
// Create a resource at /users that is attached to list-identities

// include::APIs.adoc[leveloffset=+1]

// [[authorization]]
// include::Authorization.adoc[leveloffset=+1]

include::NextSteps.adoc[leveloffset=+1]

include::AppDevelopment.adoc[leveloffset=+1]

include::Glossary.adoc[]

= Appendices

[[ch-domain-configuration]]
[appendix]
include::DomainConfiguration.adoc[leveloffset=+1]

[bibliography]
= References

bibliography::[]

[index]
== Index

// Local Variables:
// mode: outline
// outline-regexp: "[=]+"
// End:
