= Remotely configuring Site via the System API
:toc: left

In this chapter, we'll use the *site* tool as an _OAuth2 client_ to call the System API of our Site instance.

We must have first registered `site` as a client with the Site instance, which we did in <<site-cli-registration>>.

Ideally, we want to authenticate ourselves as a valid user so that Site can create a log of the individuals that requested each operation.

We don't yet have any users registered with our Site instance.
We can only create users if we can present an access token with the request.
However, we do have a client secret for the site tool that is authorized to create users.

Therefore, we will take the following steps:

. Acquire an _access token_ using our client secret (<<acquire-site-bearer-token-client-credentials>>)
. Use this access token to create a new user, with a password
. Acquire a new access token, this time authenticating using the password

[[acquire-site-bearer-token-client-credentials]]
== Acquiring a bearer token using our client secret

We can acquire an access token by making a request to the token endpoint we created in <<bootstrap-token-endpoint>>.

[IMPORTANT]
--
Acquire and store a bearer token:

----
site request-token --client-id site-cli --grant-type client_credentials
----
--

TIP: The `client-id` parameter defaults to `site-cli`, so you can omit this if you like.

This should output something similar to the following:

----
Reading client-secret from $HOME/.cache/site/default/client-secrets/site-cli
Bearer token saved to $HOME/.curlrc
Access token expires in 86400 seconds
----

By default, the access token is saved into the `$HOME/.curlrc` file which *curl* reads every time you use it.
This means that, as a significant convenience, we can disregard the need to add the bearer token every time we use curl.
The simplifies the instructions in the rest of this guide, but remember that many of the usages of curl only work because we have acquired this bearer token and saved it to `$HOME/.curlrc`.
If the token expires, some of the examples later on will fail.

[TIP]
--
At any time, you can check the current access token with the following:

----
site check-token
----

This should return a JSON object containing a property for `bearer-token`.
--

== Create a user

Now we have authorized access to the System API, we can add a user (or set of users).

To create a user we need to craft a JSON object that contains a username, but can contain any other data as necessary.  See <<ex-create-a-user>> for an example.

[[ex-create-a-user]]
.Creating a user with a password
****
Using *jo* we can create the necessary JSON for a user with username `alice`.
We can then pipe this JSON into curl to create the user.

----
jo username=alice fullname="Alice Carroll" password=$(gum input --password) \
| curl --json @- http://localhost:4444/_site/users
----
****

[IMPORTANT]
--
Create a user to represent yourself as shown in <<ex-create-a-user>>.
--

If successful, we should be able to view the user by querying for the full list of users:

----
curl http://localhost:4444/_site/users
----

This should output the following:

----
[{"fullname":"Alice Carroll","xt/id":"http://localhost:4444/_site/users/alice"}]
----

== Acquiring a bearer token using our password


----
site request-token --client-id site-cli --grant-type password \
--username alice --password password=$(gum input --password)
----

// Local Variables:
// mode: outline
// outline-regexp: "[=]+"
// End:
