= Configuration with `site`
:toc: left

Before you begin this chapter, make sure you have a record of the _client secret_ you were given in <<initialisation>>.

==



== Listing resources

[TIP]
--
Whenever you like, you can inspect your Site instance's resources with `site ls`:

----
site ls
----

This will bring up a list of all the resources in the database allowing you to narrow your search.

You can also narrow your search by providing a filter on the command line:

----
site ls operations
----

Once you have selected the resource, a representation of the resource's configuration and state will be output on the console.

Of course, this command is only available via the local admin server and not available remotely.
--

== Adding API support

In Site, resources are created by calling operations.
We must add the operations needed to build an API:

[IMPORTANT]
--
Install the `juxt/site/api-operations` group:

----
site bundle juxt/site/api-operations | curl -K $SITE_HOME/install.curl
----
--

== Install the System API

Site can be configured remotely, via its own API, which we need to install now.

[IMPORTANT]
--
Install the Site System API

----
site bundle juxt/site/system-api | curl -K $SITE_HOME/install.curl
----
--

[[bootstrap-token-endpoint]]
== Configure Site to issue bearer tokens

We must now add an endpoint that an API client can call to be authorized to call our System API.
This endpoint is called a 'token endpoint' because it issues access tokens to authorized clients to use in API requests.

[IMPORTANT]
--
Install a token endpoint for issuing bearer tokens:

----
site bundle juxt/site/oauth-token-endpoint | curl -K $SITE_HOME/install.curl
----
--

By default, access tokens are JSON Web Tokens (JWTs).
These are cryptographically signed.
We must install a keypair that Site can use to sign the JWTs that it will issue.

[IMPORTANT]
--
Install a new keypair:

----
site new-keypair | curl -K $SITE_HOME/install.curl
----
--

****
You can also use `site new-keypair` whenever you want to rotate the keypair.
Existing keypairs will be retained in the database in order to verify access tokens that have been signed in the past.
****

== Register applications

Before an application is allowed to access an API of a Resource Server, it must first be registered as a client.

[[site-cli-registration]]
=== site-cli

The `site` command-line tool can call the System API, remotely and securely, as an OAuth2 _client_.
However, to make secure API calls, the tool must be registered as a client with our Site instance.
In order to do so, we must register it with our Site instance.
We register it with the `client_id` set to `site-cli`.

Also, there are certain API endpoints of the System API that require certain permissions.
To provide the `site` tool with these permissions, we also assign a particular role to the application.
Fortunately, we can do this by installing the `juxt/site/system-client` bundle, giving `site-cli` as a parameter.

[IMPORTANT]
--
Register `site` as a client:

----
site bundle juxt/site/system-client --client-id site-cli \
| curl -K $SITE_HOME/install.curl
----
--

=== InSite

There is also a web application, called *InSite*, which can be used in preference to the command line tool.

[IMPORTANT]
--
Register the *InSite* application:

----
site bundle juxt/site/system-client --client-id insite \
| curl -K $SITE_HOME/install.curl
----
--

== Extract the client secret of an API client

Each of the applications we have registered will have a unique _client secret_.
Until we have added user accounts, we will have to use this client secret in order to authorize the application to call the System API.
Therefore, we must extract the client secret for the application we want to use.

For example, if we want to use the *InSite* web application, we must give it its unique `client_secret`:

----
site client-secret insite
----

This will return a special string of characters that we can give to *InSite* when we connect it to our Site instance.

If we give a `--save` option, it will save the `client_secret` to a temporary area known to the site-cli script (usually `$HOME/.cache/site/client-secrets/site-cli`).

[IMPORTANT]
--
Extract the client secret for this `site-cli` and save it to a temporary area:

----
site client-secret --save site-cli
----
--

In this chapter, we'll use the *site* tool to create a user account.

Ideally, we want to authenticate ourselves as a valid user so that Site can create a log of the individuals that requested each operation.

We don't yet have any users registered with our Site instance.
We can only create users if we can present an access token with the request.
However, we do have a client secret for the site tool that is authorized to create users.

Therefore, we will take the following steps:

. Acquire an _access token_ using our client secret (<<acquire-site-bearer-token-client-credentials>>)
. Use this access token to create a new user, with a password
. Acquire a new access token, this time authenticating using the password

WARNING: We must have first registered `site` as a client with the Site instance, which we did in <<site-cli-registration>>.

[[acquire-site-bearer-token-client-credentials]]
== Acquiring a bearer token using our client secret

We can acquire an access token by making a request to the token endpoint we created in <<bootstrap-token-endpoint>>.

[IMPORTANT]
--
Acquire and store a bearer token:

----
site request-token --client-id site-cli --grant-type client_credentials
----
--

TIP: The `client-id` parameter defaults to `site-cli`, so you can omit this if you like.

This should output something similar to the following:

----
Reading client-secret from $HOME/.cache/site/default/client-secrets/site-cli
Bearer token saved to $HOME/.curlrc
Access token expires in 86400 seconds
----

By default, the access token is saved into the `$HOME/.curlrc` file which *curl* reads every time you use it.
This means that, as a significant convenience, we can disregard the need to add the bearer token every time we use curl.
The simplifies the instructions in the rest of this guide, but remember that many of the usages of curl only work because we have acquired this bearer token and saved it to `$HOME/.curlrc`.
If the token expires, some of the examples later on will fail.

[TIP]
--
At any time, you can check the current access token with the following:

----
site check-token
----

This should return a JSON object containing a property for `bearer-token`.
--

== Create a user

Now we have authorized access to the System API, we can add a user (or set of users).

To create a user we need to craft a JSON object that contains a username, but can contain any other data as necessary.  See <<ex-create-a-user>> for an example.

[[ex-create-a-user]]
.Creating a user with a password
****
Using *jo* we can create the necessary JSON for a user with username `alice`.
We can then pipe this JSON into curl to create the user.

----
jo username=alice fullname="Alice Carroll" password=$(gum input --password) \
| curl --json @- http://localhost:4444/_site/users
----
****

[IMPORTANT]
--
Create a user to represent yourself as shown in <<ex-create-a-user>>.
--

If successful, we should be able to view the user by querying for the full list of users:

----
curl http://localhost:4444/_site/users
----

This should output the following:

----
[{"fullname":"Alice Carroll","xt/id":"http://localhost:4444/_site/users/alice"}]
----

== Acquiring a bearer token using our user's password

Now that we have created a user, we can use it to acquire a new bearer token.

----
site request-token --client-id site-cli --grant-type password \
--username alice --password password=$(gum input --password)
----

[IMPORTANT]
--
Request a new access token using the username and password for the user you have just created.
--

We'll use this new bearer token to continue configuring our Site instance.

Now that we're properly logged in as a known user, we can optionally disable the `client_credentials` grant type for the `site-cli` client.
This will mean that it can no longer be used.

NOTE: TODO

// Local Variables:
// mode: outline
// outline-regexp: "[=]+"
// End:
