= Configuration
:toc: left

== Configure the Site instance

The Site instance requires a configuration file, which specifies important settings such as the base-uri used for new resources, port numbers and the database configuration.

For the purposes of this guide, we'll configure a Site instance to work locally on a development machine.

If you are wanting to serve an API over a network, refer to <<ch-domain-configuration>>.

[IMPORTANT]
--
Copy `$SITE_HOME/server/etc/config/local-development.edn` to `$HOME/.config/site/config.edn`:

----
mkdir -p $HOME/.config/site
cp $SITE_HOME/server/etc/config/local-development.edn $HOME/.config/site/config.edn
----
--

== Understanding the configuration

The `local-development.edn` configuration instructs our Site instance to run two HTTP listeners, since we want to clearly separate the OAuth2 roles of the Authorization Server (AS) and Resource Server (RS).
In this configuration, Authorization Server resources start with `http://localhost:4440` and the Resource Server resources start with `http://localhost:4444`.

An additional listener is configured which is bound to `localhost` and not accessible over a network.
This listener is used for restricted operations, such as bootstrapping the Site instance with sufficient resources such that it can be securely configured from a remote client.
By default, this listener port is 4911.

The configuration also tells Site where the XTDB database files should be stored.
It's important that this is on a disk with sufficient performance and capacity.

Review the config at `$HOME/.config/site/config.edn` and feel free to make any appropriate modifications to reflect your local environment.

// Local Variables:
// mode: outline
// outline-regexp: "[=]+"
// End:
