= Running in a container
:toc: left

To simplify installation, it's possible to run the application inside an OCI-compatible container.
This is possible for both the server & the command line tool; with a simple alias you'll also be able to transparently interact with the container!

Following this approach means none of the dependencies in the Preparation step are needed.

Popular interfaces for this include Docker, Podman & Kubernetes.

Instructions here will be focused around Podman, but for these purposes Docker's CLI is 1:1.

== Dependencies

Install Docker.

----
docker --version
Docker version 24.0.6, build ed223bc820
----

Refer to the instructions for your platform to ensure Docker is working properly and you are able use Docker as a non-root user:

----
docker ps
----

****
Alternatively, install podman.

----
podman --version
podman version 4.6.0
----
****

== Build the image

Firstly, we have to build our image.
TIP: If you'd rather just pull from our Github Container Registry, skip this section.

A Dockerfile is provided at the root of the repository, so ensure that your terminal working directory is there.

----
cd $SITE_HOME
----

Build the image:

----
docker build . -t site-server
----

****
Alternatively:

----
podman build . -t site-server --format docker
----

NOTE: The `--format docker` flag is only needed for Podman as the Dockerfile includes a `HEALTHCHECK` command, otherwise for Docker run without that flag.
****

TIP: For Arch Linux users, you may need to configure rootless podman or run `podman` with `sudo`.

== Download the container

Rather than building the container yourself, you can pull down the container from the GitHub Container Registry:

----
docker pull ghcr.io/juxt-site/site-server:latest
----

== Run the container

Now you have an image built, or pulled from the GitHub Container Registry, you can run the container.
This will set-up everything the container needs for site and return a healthy status when the server can be queried.

----
docker run --net host site-server
----

The first time you run this container,

****
Alternatively:

----
podman run --net host site-server
----
****

[NOTE]
The `--net host` command is needed here as the internal admin server relies on being run on `localhost` for security reasons.
As such, it's not reachable from the outside unless you specify that the container should use the host's network instead, allowing `localhost` to resolve against the host rather than the container.
Without this flag, nothing will be able to connect to the admin server.

== Last steps

With that being complete, you should have a running instance of Site.
But how can you query it without anything installed on the host?

Well, you can simply alias the `site` CLI using the following alias:

----
alias site='docker exec -it $(docker ps -qf ancestor=site-server) site'
----

Alternatively, with podman:

----
alias site='podman exec -it $(podman container ls --filter=ancestor=localhost/site-server --format "{{.ID}}") site'
----

Assuming that you've kept the same tag name, you should be able to invoke `site` commands from anywhere.
Add that alias to your `~/.profile` or other location your shell will source from.

// Local Variables:
// mode: outline
// outline-regexp: "[=]+"
// End:
