= Preparation
:toc: left
:clj-version: 1.11.1
:bb-version: 1.1.172
:gum-version: 0.10.0
:curl-version: 8.0.0
:java-version: 17
:jo-version: 1.9

== Dependencies

Before we get started, let's check some dependencies.

<<gs-dependencies>> shows a table of dependencies that we will need to install before we can get started with Site.

[[gs-dependencies]]
.Required dependencies -- *bold* denotes a required dependency
[options=header,unbreakable,cols="3,3,5m"]
|===
|Name|Command|Minimum version
|<<install-java,*java*>>|java|{java-version}
|<<install-clojure,*Clojure*>>|clj|{clj-version}
|<<install-babashka,*Babashka*>>|bb|{bb-version}
|<<install-gum,*gum*>>|gum|{gum-version}
|<<install-curl,curl>>|curl|{curl-version}
|<<install-jo,jo>>|jo|{jo-version}
|===

[[install-java]]
=== Java

Site runs on the JVM, and requires a modern installation.

----
java -version
openjdk 20.0.1 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9)
OpenJDK 64-Bit Server VM (build 20.0.1+9, mixed mode, sharing)
----

[[install-clojure]]
=== Clojure

Site is written in Clojure, and requires Clojure to be installed on your machine.
Ensure you have https://clojure.org/[Clojure] version v{clj-version} or later installed:

----
clj --version
Clojure CLI version 1.11.1.1273
----

[[install-babashka]]
=== Babashka

Site uses Babashka for some tools and scripting.
Ensure you have https://github.com/babashka/babashka[Babashka] version v{bb-version} or later installed:

----
bb --version
babashka v1.1.172
----

[[install-gum]]
=== gum

Some of Site's scripts make use of https://github.com/charmbracelet/gum/[*gum*], which gives a nicer command-line experience.
Ensure you have *gum* installed.

----
gum --version
gum version {gum-version} (0f0f8e9)
----

For example, on Arch Linux you can install *gum* with the following:

----
pacman -S gum
----

[[install-curl]]
==== curl

For testing certain operations, we will be using https://curl.se/[*curl*].
Check you have *curl* on your system

----
curl --version
----

[[install-jo]]
==== jo

For creating JSON easily on the command line, we'll be using *jo*.
Check you have *jo* on your system.

----
jo -v
jo {jo-version}
----

== Cloning the Site source repository

[IMPORTANT]
--
Clone Site's repository to your computer, and change the current directory to `site`.

----
$ git clone https://github.com/juxt-site/site
$ cd site
----
--

== Configure your shell

We should configure the `SITE_HOME` environment variable to point to the location of the cloned the Site git repo.

The `$SITE_HOME/bin` directory contains the `site` command line tool that we will be using through this guide.

The `$SITE_HOME/server/bin` contains some scripts that are useful when you are running a Site instance on your local machine.
Since this is what we're going to be doing in this guide, we'll add both directories to our `PATH` environment variable.

Also, it is very useful to be able to tab-complete `site` commands, so let's configure your shell.

Here are the instructions for <<zsh,`zsh`>>, <<bash,`bash`>> and <<fish,`fish`>>.

[[zsh]]
=== zsh

[IMPORTANT]
--
Add this to your .zshrc:

[source]
----
export SITE_HOME=$HOME/src/github.com/juxt-site/site
export PATH=$SITE_HOME/bin:$SITE_HOME/server/bin:$PATH

_site_tasks() {
    local matches=(`site tasks |tail -n +3 |cut -f1 -d ' '`)
    compadd -a matches
}
compdef _site_tasks site
----
--

[[bash]]
=== bash

[IMPORTANT]
--
Add this to your .zshrc to get tab-complete feature on ZSH.

[source]
----
export SITE_HOME=$HOME/src/github.com/juxt-site/site
export PATH=$SITE_HOME/bin:$SITE_HOME/server/bin:$PATH

_site_tasks() {
    COMPREPLY=( $(compgen -W "$(site tasks |tail -n +3 |cut -f1 -d ' ')" -- ${COMP_WORD
S[COMP_CWORD]}) );
}
complete -F _site_tasks site
----
--

[[fish]]
=== fish

[IMPORTANT]
--
Ensure your `.config/fish/config.fish` file sets the `SITE_HOME` and `PATH` environment variables appropriately:

[source]
----
if status is-interactive
    # Commands to run in interactive sessions can go here
    set -gx SITE_HOME $HOME/site
    fish_add_path $SITE_HOME/bin $SITE_HOME/server/bin
end
----
--


[IMPORTANT]
--
Add this to your .config/fish/completions/site.fish to get tab-complete feature on Fish shell.

[source]
----
function __site_complete_tasks
  if not test "$__site_tasks"
    set -g __site_tasks (site tasks |tail -n +3 |cut -f1 -d ' ')
  end

  printf "%s\n" $__site_tasks
end

complete -c site -a "(__site_complete_tasks)" -d 'tasks'
----
--


// Local Variables:
// mode: outline
// outline-regexp: "[=]+"
// End:
