= Server Initialisation
:toc: left

In this chapter we will add just enough resources to a Site instance's database to build up a working 'System API'.

Once we have built this API we can continue to configure Site remotely by using an API client.

== Introducing `site`

`site` is a command line tool that allows us to initialise, configure and administer a Site instance.

For the remainder of this 'getting started' guide, we'll work with its default configuration.

However, if you ever _do_ need to change some of its defaults, refer to <<ch-site-cli-configuration>>.

== Checking the Server

You can use `site` to to check whether a Site instance is up.

----
site ping
----

If your Site instance is up and running, this should respond with:

----
Checking http://localhost:4444/_site/healthcheck
Response: Site OK!
----

== Resetting the Server

When configuring a Site instance, all the resources are stored in the database.

If you ever need to start over, you can delete all resources from a Site instance.

----
site reset
----

[WARNING]
--
Be careful, this is a dangerous command!
--

[[initialisation]]
== Initialisation

Next we must initialise Site by deploying a minimal set of resources.

We do this by calling `site init`.

[IMPORTANT]
--
Initialise your Site instance:

----
site init
----
--

The initialization process registers some clients with the Site instance, displaying a _client secret_ for each.

== Querying resources

NOTE: These commands is only available via the local admin server and not available remotely.

If you are on the same host as a running Site instance, you can list its resources with `site list`:

----
site list
----

This will bring up a list of all the resources in the database allowing you to narrow your search.

You can also narrow your search by providing a filter on the command line:

----
site list operations
----

A more powerful command is `site find`.
This works in a similar way to `site list` but will output the current state and configuration of a resource.

----
site find operations
----

If the argument to find would return more than one result, you will be given a choice to further narrow the search to the resource you wish to view.
A representation of the resource's configuration and state will be output on the console.

== Querying client secrets

Often it is necessary to get the client secret for an application that has been registered with a Site instance.
[source]
----
site client-secret insite
----

If we give a `--save` option, it will save the `client_secret` to a temporary area known to the site-cli script (usually `$HOME/.cache/site/client-secrets/site-cli`).

== What next?

We are now at a fork in the road, where it is up to you to make a decision.

Run `site status` to output the instructions which contain the up-to-date client secrets.

[source]
----
site status
----

This should output the available choices.

[source]
----
You should now continue to configure your Site instance,
using one of the following methods:

A. Proceed to https://insite.juxt.site?client-secret=246194743141bdd8f74c613c3c8f4f5169450a2b
 or
B. Continue with this site tool, acquiring an access token with:
site request-token --client-secret 0d0cfdd61ff09bae7a7523144a7439a3046d6703
----

If you wish to proceed with a more visual and intuitive configuration experience, we recommend our *InSite* web application.
Open a browser at the web link displayed in the output of `site init` and proceed to <<configuration-with-insite>>.

If you prefer to continue with the command-line experience offered by the `site` tool, then copy the command displayed in the output of `site init` and proceed to <<configuration-with-site>>.

// Local Variables:
// mode: outline
// outline-regexp: "[=]+"
// End:
